<a href="https://colab.research.google.com/github/AsifShaik18/Mental-Fitness-Tracker/blob/main/Mental_Fitness_Tracker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
from math import sqrt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [ ]:
# Read the dataset
dataset = pd.read_csv("Mental-Fitness.csv")
dataset.head()

Country  Year  Bipolar disorder   Eating disorders   \
0  Afghanistan  1990           0.721207           0.131001   
1  Afghanistan  1991           0.719952           0.126395   
2  Afghanistan  1992           0.718418           0.121832   
3  Afghanistan  1993           0.717452           0.117942   
4  Afghanistan  1994           0.717012           0.114547   

   Anxiety disorders   Drug use disorders   Depressive disorders   \
0            4.835127             0.454202               5.125291   
1            4.821765             0.447112               5.116306   
2            4.801434             0.441190               5.106558   
3            4.789363             0.435581               5.100328   
4            4.784923             0.431822               5.099424   

   Alcohol use disorders   Mental Fitness  
0                0.444036        1.696670  
1                0.444250        1.734281  
2                0.445501        1.791189  
3                0.445958        1.776779  
4                0.445779        1.712986

In [ ]:
# Splitting the dataset into input features (X) and target variable (Y)
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [ ]:
X

array([['Afghanistan', 1990, 0.721206856, ..., 0.454202284, 5.125291308,
        0.444036259],
       ['Afghanistan', 1991, 0.719952483, ..., 0.447111566, 5.116306482,
        0.444249651],
       ['Afghanistan', 1992, 0.718417542, ..., 0.441190164, 5.106558027,
        0.445500928],
       ...,
       ['Zimbabwe', 2017, 0.562612419, ..., 0.608095943, 3.564137646,
        1.651805112],
       ['Zimbabwe', 2018, 0.563283467, ..., 0.609065117, 3.563141259,
        1.686710927],
       ['Zimbabwe', 2019, 0.56382022, ..., 0.610644338, 3.554570866,
        1.776729434]], dtype=object)

In [ ]:
Y

array([1.69667048, 1.73428137, 1.79118945, ..., 2.36426505, 2.47294913,
       2.52589178])

In [ ]:
#This line imports the Plotly Express library, which is used for interactive data visualization.
import plotly.express as px
#This code segment generates a line plot using Plotly Express. It visualizes the relationship between the "Country" and "Mental Fitness" columns from the 'dataset'.
fig=px.line(dataset,x="Country",y="Mental Fitness")
fig.show()

In [ ]:
#This code segment generates a scatter plot using Plotly Express. It visualizes the relationship between the "Country" and "Mental Fitness" columns from the 'dataset'.
import plotly.express as px
fig = px.scatter(dataset, x="Country", y="Mental Fitness")
fig.show()

In [ ]:
#This code segment generates a box plot using Plotly Express. It visualizes the distribution of the "Mental Fitness" values based on different levels of the "Counytry".
import plotly.express as px
fig = px.box(dataset, x="Country", y="Mental Fitness")
fig.show()

In [ ]:
#This code segment generates a histogram using Plotly Express. It visualizes the distribution of the "Mental Fitness" values with 10 bins.
import plotly.express as px
fig = px.histogram(dataset, x="Mental Fitness", nbins=10)
fig.show()

In [ ]:
'''
This code segment generates a bar chart using Plotly Express. It visualizes the relationship between the "Country" and "Mental Fitness" columns,
with the bars colored based on the "Country" values.
'''
import plotly.express as px
fig = px.bar(dataset, x="Country", y="Mental Fitness", color="Country")
fig.show()

In [ ]:
'''
This code segment generates a 3D scatter plot using Plotly Express. It visualizes the relationship between the "Country", "Year", and "Mental Fitness" columns
from the 'dataset', with the color representing the "Mental Fitness" values.
'''
import plotly.express as px
fig = px.scatter_3d(dataset, x="Country", y="Year", z="Mental Fitness",color="Mental Fitness")
fig.show()

In [ ]:
# Perform one-hot encoding on categorical features
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'
)
X = ct.fit_transform(X)

In [ ]:
X

<6809x234 sparse matrix of type '<class 'numpy.float64'>'
	with 54472 stored elements in Compressed Sparse Row format>

In [ ]:
# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [ ]:
X_train

<5447x234 sparse matrix of type '<class 'numpy.float64'>'
	with 43576 stored elements in Compressed Sparse Row format>

In [ ]:
X_test

<1362x234 sparse matrix of type '<class 'numpy.float64'>'
	with 10896 stored elements in Compressed Sparse Row format>

In [ ]:
Y_train

array([7.02907413, 4.24817971, 4.32288633, ..., 5.24592077, 6.02423665,
       1.89458115])

In [ ]:
Y_test

array([3.58144034, 6.00104379, 1.95914535, ..., 8.66827659, 1.26260571,
       8.06170993])

In [ ]:
# Standardize the data
ss = StandardScaler(with_mean=False)
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [ ]:
X_train

<5447x234 sparse matrix of type '<class 'numpy.float64'>'
	with 43576 stored elements in Compressed Sparse Row format>

In [ ]:
X_test

<1362x234 sparse matrix of type '<class 'numpy.float64'>'
	with 10896 stored elements in Compressed Sparse Row format>

In [ ]:
# Create and train the RandomForestRegressor model
regressor = RandomForestRegressor()
regressor.fit(X_train, Y_train)

RandomForestRegressor()

In [ ]:
# Predict the mental fitness for a new person
# Predict the mental fitness for a new person
Person_data = [['India', 1990, 0.721207, 0.131001, 4.835127, 0.454202, 5.125291, 0.444036]]
Person_data_encoded = ct.transform(Person_data)
Mental_Fitness = regressor.predict(Person_data_encoded)
print("Predicted Mental Fitness of the Person:", Mental_Fitness)

Predicted Mental Fitness of the Person: [4.8228862]


In [ ]:
# Calculate the R-squared score( Accuracy )
Y_pred = regressor.predict(X_train)
r2 = r2_score(Y_train, Y_pred)
print("R-squared Score:", r2)

R-squared Score: 0.9991410650437447
